source "http://rubygems.org"
gem "activerecord", "4.2.0"
gem "bson_ext", "~> 1.11.1"
gem "curb", "~> 0.7.18"
gem "htmlentities"
gem "json", "~> 1.7"
gem "nokogiri", "~> 1.5.0"
gem "retries", "~> 0.0.5"
gem "sqlite3", "~> 1.3"
